### PR TITLE
Add all-your-base exercise

### PR DESCRIPTION
**Pull request by mienaikage**

### CODE REVIEW

**Comment by mienaikage** [comment]
Needs https://github.com/exercism/xperl6/pull/55 for travis to pass.

**Comment by kytrinyx** [comment]
Would you mind rebasing against master so we can test that this does pass the build?

**Comment by mienaikage** [comment]
Done!

**Comment by mienaikage** [comment]
Added in a minor change before merging. (It's how I'd originally tried to write it but I had no idea what the operator to do so was before now...)

**Comment by mienaikage** [comment]
https://github.com/exercism/x-common/pull/466 was created to change `output_digits` to `expected`. Made this change here to keep data in line with canonical-data.

**Comment by kotp** [comment]
Would it be something we should work on to take the canonical data and generate the tests from that automatically?

This way, when they change, it is a matter of, hopefully, simply running the generator to update the tests?

**Comment by mienaikage** [comment]
I'm thinking of writing a script to pull canonical-data from x-common and give us a cases.json file to work from. Not too sure about generating the tests themselves automatically though, as the test cases aren't always cut and dry.

**Comment by kotp** [comment]
Peek at what we have done in the [xruby track](https://github.com/exercism/xruby/blob/master/bin/generate#L3) <- that points to the generate code, hints are in there.  I am available to walk through what happens, if you want.

**Comment by mienaikage** [comment]
Likely worth raising an issue to plan out how we want to do this.

**Comment by mienaikage** [comment]
Modified some tests to check for exceptions.

Note that Travis will fail until https://github.com/exercism/xperl6/pull/71 is merged.

**Pull request merged**
