### PR TITLE
port exercise 'luhn' to Perl 6

### PR DESCRIPTION
**Pull request by yanick**

### CODE REVIEW

**Comment by yanick** [comment]
test plan added

**Comment by mienaikage** [comment]
I've created a discussion for `Test` in https://github.com/exercism/xperl6/issues/85 and would value your opinion 🙂

**Comment by mienaikage** [comment]
Sorry for being so slow. I'd given it a quick look over before but I've not done the exercise in another language myself so I'm not familiar with it.

It looks like about 4 weeks ago the exercise was rewritten. There's an issue open for it on xperl5 requesting it be rewritten I believe, but there wasn't one here as we didn't yet have an implementation: https://github.com/exercism/x-common/pull/474

Could we modify this to behave more like the newer version?

**Comment by mienaikage** [comment]
We might want to hold off a bit because it looks like there's still a pull request open for changes to the exercise: https://github.com/exercism/x-common/pull/522

**Comment by yanick** [comment]
rebase to master

**Comment by mienaikage** [comment]
It'd be good to simplify this, the exercise in `canonical-data` only requires validation now. It might be worth having a look in this repos `bin/` directory and giving the generator a go 🙂

**Comment by mienaikage** [comment]
To keep things in line with x-common I've simplified the exercise to only check validity. The canonical-data from x-common is also used here, via the generator. I can squash these commits and merge if you're okay with these changes, or if there's anything you'd like to change with this feel free to comment/commit!

**Comment by yanick** [comment]
> I can squash these commits and merge if you're okay with these changes

It's all good. :+1:

**Pull request merged**
