### PR TITLE
Include x-common as submodule

### PR DESCRIPTION
**Pull request by mienaikage**
Including this to be able to test if any canonical-data used is up to date with what's in x-common.

### CODE REVIEW

**Comment by kytrinyx** [comment]
By adding this we now have two copies of x-common in the `trackler` gem. I'd appreciate it if we could find another way.

**Comment by mienaikage** [comment]
Hmm... Maybe I can take it out of the repo and clone within Travis. I'll take a look when I get home.

**Comment by mienaikage** [comment]
Changes in https://github.com/exercism/xperl6/pull/131, sorry about that 😓

**Comment by kytrinyx** [comment]
:heart: thanks so much!

**Pull request merged**
